### ISSUE TITLE
想问问关于react的全栈架构

### ISSUE THREAD

**Issue by Restry** [shimohq/react-cookbook#4]
https://medium.com/@bryantheastronaut/react-getting-started-the-mern-stack-tutorial-feat-es6-de1a2886be50

这个是国外的一个getting-started..我也不知道这一句怎样翻译好，哈哈。
里面推荐的是MERN（MongoDB/Express/React/Node.js）全栈架构。我想了解一下现在主流的前端+后端的架构是什么样子的，请赐教：）

**Comment by yarcowang** [comment]
少年, 还是玩PHP吧... ;)
